//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientAnaSayfa.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Test", ReplyAction="http://tempuri.org/IService1/TestResponse")]
        bool Test();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Test", ReplyAction="http://tempuri.org/IService1/TestResponse")]
        System.Threading.Tasks.Task<bool> TestAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/TestDataTable", ReplyAction="http://tempuri.org/IService1/TestDataTableResponse")]
        System.Data.DataTable TestDataTable();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/TestDataTable", ReplyAction="http://tempuri.org/IService1/TestDataTableResponse")]
        System.Threading.Tasks.Task<System.Data.DataTable> TestDataTableAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getDBVersion", ReplyAction="http://tempuri.org/IService1/getDBVersionResponse")]
        string getDBVersion();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getDBVersion", ReplyAction="http://tempuri.org/IService1/getDBVersionResponse")]
        System.Threading.Tasks.Task<string> getDBVersionAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Users_kullaniciEkle", ReplyAction="http://tempuri.org/IService1/Users_kullaniciEkleResponse")]
        string Users_kullaniciEkle(string firstName, string lastName, string tcNo, string password, int role, string mail, string phoneNo, string address, int gender);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Users_kullaniciEkle", ReplyAction="http://tempuri.org/IService1/Users_kullaniciEkleResponse")]
        System.Threading.Tasks.Task<string> Users_kullaniciEkleAsync(string firstName, string lastName, string tcNo, string password, int role, string mail, string phoneNo, string address, int gender);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Users_kullaniciSil", ReplyAction="http://tempuri.org/IService1/Users_kullaniciSilResponse")]
        bool Users_kullaniciSil(int userID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Users_kullaniciSil", ReplyAction="http://tempuri.org/IService1/Users_kullaniciSilResponse")]
        System.Threading.Tasks.Task<bool> Users_kullaniciSilAsync(int userID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Users_kullaniciGuncelle", ReplyAction="http://tempuri.org/IService1/Users_kullaniciGuncelleResponse")]
        string Users_kullaniciGuncelle(string firstName, string lastName, string tcNo, string password, int role, string mail, string phoneNo, string address, int gender, int userID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Users_kullaniciGuncelle", ReplyAction="http://tempuri.org/IService1/Users_kullaniciGuncelleResponse")]
        System.Threading.Tasks.Task<string> Users_kullaniciGuncelleAsync(string firstName, string lastName, string tcNo, string password, int role, string mail, string phoneNo, string address, int gender, int userID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Users_kullanicilariGetir", ReplyAction="http://tempuri.org/IService1/Users_kullanicilariGetirResponse")]
        System.Data.DataTable Users_kullanicilariGetir();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Users_kullanicilariGetir", ReplyAction="http://tempuri.org/IService1/Users_kullanicilariGetirResponse")]
        System.Threading.Tasks.Task<System.Data.DataTable> Users_kullanicilariGetirAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Users_garsonlariGetir", ReplyAction="http://tempuri.org/IService1/Users_garsonlariGetirResponse")]
        System.Data.DataTable Users_garsonlariGetir();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Users_garsonlariGetir", ReplyAction="http://tempuri.org/IService1/Users_garsonlariGetirResponse")]
        System.Threading.Tasks.Task<System.Data.DataTable> Users_garsonlariGetirAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Users_yoneticileriGetir", ReplyAction="http://tempuri.org/IService1/Users_yoneticileriGetirResponse")]
        System.Data.DataTable Users_yoneticileriGetir();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Users_yoneticileriGetir", ReplyAction="http://tempuri.org/IService1/Users_yoneticileriGetirResponse")]
        System.Threading.Tasks.Task<System.Data.DataTable> Users_yoneticileriGetirAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Users_kullaniciGiris", ReplyAction="http://tempuri.org/IService1/Users_kullaniciGirisResponse")]
        bool Users_kullaniciGiris(int userID, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Users_kullaniciGiris", ReplyAction="http://tempuri.org/IService1/Users_kullaniciGirisResponse")]
        System.Threading.Tasks.Task<bool> Users_kullaniciGirisAsync(int userID, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Users_kullaniciVarmi", ReplyAction="http://tempuri.org/IService1/Users_kullaniciVarmiResponse")]
        bool Users_kullaniciVarmi(int userID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Users_kullaniciVarmi", ReplyAction="http://tempuri.org/IService1/Users_kullaniciVarmiResponse")]
        System.Threading.Tasks.Task<bool> Users_kullaniciVarmiAsync(int userID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Users_kullaniciBilgileriniGetir", ReplyAction="http://tempuri.org/IService1/Users_kullaniciBilgileriniGetirResponse")]
        System.Data.DataTable Users_kullaniciBilgileriniGetir(int userID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Users_kullaniciBilgileriniGetir", ReplyAction="http://tempuri.org/IService1/Users_kullaniciBilgileriniGetirResponse")]
        System.Threading.Tasks.Task<System.Data.DataTable> Users_kullaniciBilgileriniGetirAsync(int userID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Users_kullaniciAdSoyadGetir", ReplyAction="http://tempuri.org/IService1/Users_kullaniciAdSoyadGetirResponse")]
        string Users_kullaniciAdSoyadGetir(int userID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Users_kullaniciAdSoyadGetir", ReplyAction="http://tempuri.org/IService1/Users_kullaniciAdSoyadGetirResponse")]
        System.Threading.Tasks.Task<string> Users_kullaniciAdSoyadGetirAsync(int userID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Users_tumGarsonlarinAdSoyadlari", ReplyAction="http://tempuri.org/IService1/Users_tumGarsonlarinAdSoyadlariResponse")]
        System.Data.DataTable Users_tumGarsonlarinAdSoyadlari();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Users_tumGarsonlarinAdSoyadlari", ReplyAction="http://tempuri.org/IService1/Users_tumGarsonlarinAdSoyadlariResponse")]
        System.Threading.Tasks.Task<System.Data.DataTable> Users_tumGarsonlarinAdSoyadlariAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Tables_masaEkle", ReplyAction="http://tempuri.org/IService1/Tables_masaEkleResponse")]
        string Tables_masaEkle(string tableNo, int capacity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Tables_masaEkle", ReplyAction="http://tempuri.org/IService1/Tables_masaEkleResponse")]
        System.Threading.Tasks.Task<string> Tables_masaEkleAsync(string tableNo, int capacity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Tables_masaSil", ReplyAction="http://tempuri.org/IService1/Tables_masaSilResponse")]
        bool Tables_masaSil(int tableID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Tables_masaSil", ReplyAction="http://tempuri.org/IService1/Tables_masaSilResponse")]
        System.Threading.Tasks.Task<bool> Tables_masaSilAsync(int tableID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Tables_masaGuncelle", ReplyAction="http://tempuri.org/IService1/Tables_masaGuncelleResponse")]
        string Tables_masaGuncelle(string tableNo, int capacity, int tableID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Tables_masaGuncelle", ReplyAction="http://tempuri.org/IService1/Tables_masaGuncelleResponse")]
        System.Threading.Tasks.Task<string> Tables_masaGuncelleAsync(string tableNo, int capacity, int tableID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Tables_masalariGetir", ReplyAction="http://tempuri.org/IService1/Tables_masalariGetirResponse")]
        System.Data.DataTable Tables_masalariGetir();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Tables_masalariGetir", ReplyAction="http://tempuri.org/IService1/Tables_masalariGetirResponse")]
        System.Threading.Tasks.Task<System.Data.DataTable> Tables_masalariGetirAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Tables_acikMasalariGetir", ReplyAction="http://tempuri.org/IService1/Tables_acikMasalariGetirResponse")]
        System.Data.DataTable Tables_acikMasalariGetir();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Tables_acikMasalariGetir", ReplyAction="http://tempuri.org/IService1/Tables_acikMasalariGetirResponse")]
        System.Threading.Tasks.Task<System.Data.DataTable> Tables_acikMasalariGetirAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Tables_bosMasalariGetir", ReplyAction="http://tempuri.org/IService1/Tables_bosMasalariGetirResponse")]
        System.Data.DataTable Tables_bosMasalariGetir();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Tables_bosMasalariGetir", ReplyAction="http://tempuri.org/IService1/Tables_bosMasalariGetirResponse")]
        System.Threading.Tasks.Task<System.Data.DataTable> Tables_bosMasalariGetirAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Tables_masaBilgileriniGetir", ReplyAction="http://tempuri.org/IService1/Tables_masaBilgileriniGetirResponse")]
        System.Data.DataTable Tables_masaBilgileriniGetir(int tableID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Tables_masaBilgileriniGetir", ReplyAction="http://tempuri.org/IService1/Tables_masaBilgileriniGetirResponse")]
        System.Threading.Tasks.Task<System.Data.DataTable> Tables_masaBilgileriniGetirAsync(int tableID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Tables_masaAc", ReplyAction="http://tempuri.org/IService1/Tables_masaAcResponse")]
        bool Tables_masaAc(int userID, int tableID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Tables_masaAc", ReplyAction="http://tempuri.org/IService1/Tables_masaAcResponse")]
        System.Threading.Tasks.Task<bool> Tables_masaAcAsync(int userID, int tableID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Tables_masaHesapGetir", ReplyAction="http://tempuri.org/IService1/Tables_masaHesapGetirResponse")]
        string Tables_masaHesapGetir(int tableID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Tables_masaHesapGetir", ReplyAction="http://tempuri.org/IService1/Tables_masaHesapGetirResponse")]
        System.Threading.Tasks.Task<string> Tables_masaHesapGetirAsync(int tableID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Tables_masaDurumGetir", ReplyAction="http://tempuri.org/IService1/Tables_masaDurumGetirResponse")]
        bool Tables_masaDurumGetir(int tableID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Tables_masaDurumGetir", ReplyAction="http://tempuri.org/IService1/Tables_masaDurumGetirResponse")]
        System.Threading.Tasks.Task<bool> Tables_masaDurumGetirAsync(int tableID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Tables_masaKapat", ReplyAction="http://tempuri.org/IService1/Tables_masaKapatResponse")]
        bool Tables_masaKapat(int tableID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Tables_masaKapat", ReplyAction="http://tempuri.org/IService1/Tables_masaKapatResponse")]
        System.Threading.Tasks.Task<bool> Tables_masaKapatAsync(int tableID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Product_urunEkle", ReplyAction="http://tempuri.org/IService1/Product_urunEkleResponse")]
        string Product_urunEkle(int catID, string productName, string price, string description);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Product_urunEkle", ReplyAction="http://tempuri.org/IService1/Product_urunEkleResponse")]
        System.Threading.Tasks.Task<string> Product_urunEkleAsync(int catID, string productName, string price, string description);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Product_urunSil", ReplyAction="http://tempuri.org/IService1/Product_urunSilResponse")]
        string Product_urunSil(int productID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Product_urunSil", ReplyAction="http://tempuri.org/IService1/Product_urunSilResponse")]
        System.Threading.Tasks.Task<string> Product_urunSilAsync(int productID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Product_urunSiparisleriyleSil", ReplyAction="http://tempuri.org/IService1/Product_urunSiparisleriyleSilResponse")]
        bool Product_urunSiparisleriyleSil(int product);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Product_urunSiparisleriyleSil", ReplyAction="http://tempuri.org/IService1/Product_urunSiparisleriyleSilResponse")]
        System.Threading.Tasks.Task<bool> Product_urunSiparisleriyleSilAsync(int product);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Product_kategoridekiUrunleriSil", ReplyAction="http://tempuri.org/IService1/Product_kategoridekiUrunleriSilResponse")]
        bool Product_kategoridekiUrunleriSil(int catID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Product_kategoridekiUrunleriSil", ReplyAction="http://tempuri.org/IService1/Product_kategoridekiUrunleriSilResponse")]
        System.Threading.Tasks.Task<bool> Product_kategoridekiUrunleriSilAsync(int catID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Product_urunGuncelle", ReplyAction="http://tempuri.org/IService1/Product_urunGuncelleResponse")]
        string Product_urunGuncelle(string productName, string price, int status, string description, int catID, int productID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Product_urunGuncelle", ReplyAction="http://tempuri.org/IService1/Product_urunGuncelleResponse")]
        System.Threading.Tasks.Task<string> Product_urunGuncelleAsync(string productName, string price, int status, string description, int catID, int productID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Product_urunleriGetir", ReplyAction="http://tempuri.org/IService1/Product_urunleriGetirResponse")]
        System.Data.DataTable Product_urunleriGetir();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Product_urunleriGetir", ReplyAction="http://tempuri.org/IService1/Product_urunleriGetirResponse")]
        System.Threading.Tasks.Task<System.Data.DataTable> Product_urunleriGetirAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Product_akfitUrunleriGetir", ReplyAction="http://tempuri.org/IService1/Product_akfitUrunleriGetirResponse")]
        System.Data.DataTable Product_akfitUrunleriGetir();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Product_akfitUrunleriGetir", ReplyAction="http://tempuri.org/IService1/Product_akfitUrunleriGetirResponse")]
        System.Threading.Tasks.Task<System.Data.DataTable> Product_akfitUrunleriGetirAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Product_kategoriyeGoreUrunleriGetir", ReplyAction="http://tempuri.org/IService1/Product_kategoriyeGoreUrunleriGetirResponse")]
        System.Data.DataTable Product_kategoriyeGoreUrunleriGetir(int catID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Product_kategoriyeGoreUrunleriGetir", ReplyAction="http://tempuri.org/IService1/Product_kategoriyeGoreUrunleriGetirResponse")]
        System.Threading.Tasks.Task<System.Data.DataTable> Product_kategoriyeGoreUrunleriGetirAsync(int catID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Product_urunleriSiraliGetir", ReplyAction="http://tempuri.org/IService1/Product_urunleriSiraliGetirResponse")]
        System.Data.DataTable Product_urunleriSiraliGetir();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Product_urunleriSiraliGetir", ReplyAction="http://tempuri.org/IService1/Product_urunleriSiraliGetirResponse")]
        System.Threading.Tasks.Task<System.Data.DataTable> Product_urunleriSiraliGetirAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Product_kategoriyeGoreUrunleriSiraliGetir", ReplyAction="http://tempuri.org/IService1/Product_kategoriyeGoreUrunleriSiraliGetirResponse")]
        System.Data.DataTable Product_kategoriyeGoreUrunleriSiraliGetir(int catID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Product_kategoriyeGoreUrunleriSiraliGetir", ReplyAction="http://tempuri.org/IService1/Product_kategoriyeGoreUrunleriSiraliGetirResponse")]
        System.Threading.Tasks.Task<System.Data.DataTable> Product_kategoriyeGoreUrunleriSiraliGetirAsync(int catID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Product_urunBilgileriniGetir", ReplyAction="http://tempuri.org/IService1/Product_urunBilgileriniGetirResponse")]
        System.Data.DataTable Product_urunBilgileriniGetir(int productID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Product_urunBilgileriniGetir", ReplyAction="http://tempuri.org/IService1/Product_urunBilgileriniGetirResponse")]
        System.Threading.Tasks.Task<System.Data.DataTable> Product_urunBilgileriniGetirAsync(int productID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Product_urunFiyatGetir", ReplyAction="http://tempuri.org/IService1/Product_urunFiyatGetirResponse")]
        string Product_urunFiyatGetir(int productID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Product_urunFiyatGetir", ReplyAction="http://tempuri.org/IService1/Product_urunFiyatGetirResponse")]
        System.Threading.Tasks.Task<string> Product_urunFiyatGetirAsync(int productID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Product_urunDurumGuncelle", ReplyAction="http://tempuri.org/IService1/Product_urunDurumGuncelleResponse")]
        bool Product_urunDurumGuncelle(int status, int productID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Product_urunDurumGuncelle", ReplyAction="http://tempuri.org/IService1/Product_urunDurumGuncelleResponse")]
        System.Threading.Tasks.Task<bool> Product_urunDurumGuncelleAsync(int status, int productID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Product_kategoriyeAitUrunKontrol", ReplyAction="http://tempuri.org/IService1/Product_kategoriyeAitUrunKontrolResponse")]
        bool Product_kategoriyeAitUrunKontrol(int catID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Product_kategoriyeAitUrunKontrol", ReplyAction="http://tempuri.org/IService1/Product_kategoriyeAitUrunKontrolResponse")]
        System.Threading.Tasks.Task<bool> Product_kategoriyeAitUrunKontrolAsync(int catID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Orders_siparisEkle", ReplyAction="http://tempuri.org/IService1/Orders_siparisEkleResponse")]
        bool Orders_siparisEkle(int tableID, int productID, int catID, int total);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Orders_siparisEkle", ReplyAction="http://tempuri.org/IService1/Orders_siparisEkleResponse")]
        System.Threading.Tasks.Task<bool> Orders_siparisEkleAsync(int tableID, int productID, int catID, int total);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Orders_siparisSil", ReplyAction="http://tempuri.org/IService1/Orders_siparisSilResponse")]
        string Orders_siparisSil(int tableID, int productID, int total);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Orders_siparisSil", ReplyAction="http://tempuri.org/IService1/Orders_siparisSilResponse")]
        System.Threading.Tasks.Task<string> Orders_siparisSilAsync(int tableID, int productID, int total);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Orders_siparisUrunIDileSil", ReplyAction="http://tempuri.org/IService1/Orders_siparisUrunIDileSilResponse")]
        bool Orders_siparisUrunIDileSil(int productID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Orders_siparisUrunIDileSil", ReplyAction="http://tempuri.org/IService1/Orders_siparisUrunIDileSilResponse")]
        System.Threading.Tasks.Task<bool> Orders_siparisUrunIDileSilAsync(int productID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Orders_siparisIDileSil", ReplyAction="http://tempuri.org/IService1/Orders_siparisIDileSilResponse")]
        string Orders_siparisIDileSil(int orderID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Orders_siparisIDileSil", ReplyAction="http://tempuri.org/IService1/Orders_siparisIDileSilResponse")]
        System.Threading.Tasks.Task<string> Orders_siparisIDileSilAsync(int orderID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Orders_siparisCATIDileSil", ReplyAction="http://tempuri.org/IService1/Orders_siparisCATIDileSilResponse")]
        int Orders_siparisCATIDileSil(int catID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Orders_siparisCATIDileSil", ReplyAction="http://tempuri.org/IService1/Orders_siparisCATIDileSilResponse")]
        System.Threading.Tasks.Task<int> Orders_siparisCATIDileSilAsync(int catID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Orders_masaninTümSiparisleriniSil", ReplyAction="http://tempuri.org/IService1/Orders_masaninTümSiparisleriniSilResponse")]
        string Orders_masaninTümSiparisleriniSil(int tableID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Orders_masaninTümSiparisleriniSil", ReplyAction="http://tempuri.org/IService1/Orders_masaninTümSiparisleriniSilResponse")]
        System.Threading.Tasks.Task<string> Orders_masaninTümSiparisleriniSilAsync(int tableID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Orders_siparisleriGetir", ReplyAction="http://tempuri.org/IService1/Orders_siparisleriGetirResponse")]
        System.Data.DataTable Orders_siparisleriGetir();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Orders_siparisleriGetir", ReplyAction="http://tempuri.org/IService1/Orders_siparisleriGetirResponse")]
        System.Threading.Tasks.Task<System.Data.DataTable> Orders_siparisleriGetirAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Orders_masayaAitSiparisleriGetir", ReplyAction="http://tempuri.org/IService1/Orders_masayaAitSiparisleriGetirResponse")]
        System.Data.DataTable Orders_masayaAitSiparisleriGetir(int tableID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Orders_masayaAitSiparisleriGetir", ReplyAction="http://tempuri.org/IService1/Orders_masayaAitSiparisleriGetirResponse")]
        System.Threading.Tasks.Task<System.Data.DataTable> Orders_masayaAitSiparisleriGetirAsync(int tableID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Orders_urunKontrol", ReplyAction="http://tempuri.org/IService1/Orders_urunKontrolResponse")]
        bool Orders_urunKontrol(int productID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Orders_urunKontrol", ReplyAction="http://tempuri.org/IService1/Orders_urunKontrolResponse")]
        System.Threading.Tasks.Task<bool> Orders_urunKontrolAsync(int productID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Orders_masaUrunKontrol", ReplyAction="http://tempuri.org/IService1/Orders_masaUrunKontrolResponse")]
        bool Orders_masaUrunKontrol(int productID, int tableID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Orders_masaUrunKontrol", ReplyAction="http://tempuri.org/IService1/Orders_masaUrunKontrolResponse")]
        System.Threading.Tasks.Task<bool> Orders_masaUrunKontrolAsync(int productID, int tableID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DayReport_guneAitRaporGetir", ReplyAction="http://tempuri.org/IService1/DayReport_guneAitRaporGetirResponse")]
        System.Data.DataTable DayReport_guneAitRaporGetir(string date);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DayReport_guneAitRaporGetir", ReplyAction="http://tempuri.org/IService1/DayReport_guneAitRaporGetirResponse")]
        System.Threading.Tasks.Task<System.Data.DataTable> DayReport_guneAitRaporGetirAsync(string date);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DayReport_raporlariGetir", ReplyAction="http://tempuri.org/IService1/DayReport_raporlariGetirResponse")]
        System.Data.DataTable DayReport_raporlariGetir();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DayReport_raporlariGetir", ReplyAction="http://tempuri.org/IService1/DayReport_raporlariGetirResponse")]
        System.Threading.Tasks.Task<System.Data.DataTable> DayReport_raporlariGetirAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DayReport_guneAitCalisanIsimleri", ReplyAction="http://tempuri.org/IService1/DayReport_guneAitCalisanIsimleriResponse")]
        string[] DayReport_guneAitCalisanIsimleri(string date);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DayReport_guneAitCalisanIsimleri", ReplyAction="http://tempuri.org/IService1/DayReport_guneAitCalisanIsimleriResponse")]
        System.Threading.Tasks.Task<string[]> DayReport_guneAitCalisanIsimleriAsync(string date);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Category_kategoriEkle", ReplyAction="http://tempuri.org/IService1/Category_kategoriEkleResponse")]
        string Category_kategoriEkle(string catName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Category_kategoriEkle", ReplyAction="http://tempuri.org/IService1/Category_kategoriEkleResponse")]
        System.Threading.Tasks.Task<string> Category_kategoriEkleAsync(string catName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Category_kategoriSil", ReplyAction="http://tempuri.org/IService1/Category_kategoriSilResponse")]
        string Category_kategoriSil(int catID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Category_kategoriSil", ReplyAction="http://tempuri.org/IService1/Category_kategoriSilResponse")]
        System.Threading.Tasks.Task<string> Category_kategoriSilAsync(int catID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Category_kategoriUrunleriyleSil", ReplyAction="http://tempuri.org/IService1/Category_kategoriUrunleriyleSilResponse")]
        string Category_kategoriUrunleriyleSil(int catID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Category_kategoriUrunleriyleSil", ReplyAction="http://tempuri.org/IService1/Category_kategoriUrunleriyleSilResponse")]
        System.Threading.Tasks.Task<string> Category_kategoriUrunleriyleSilAsync(int catID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Category_kategoriGuncelle", ReplyAction="http://tempuri.org/IService1/Category_kategoriGuncelleResponse")]
        string Category_kategoriGuncelle(string catName, int catID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Category_kategoriGuncelle", ReplyAction="http://tempuri.org/IService1/Category_kategoriGuncelleResponse")]
        System.Threading.Tasks.Task<string> Category_kategoriGuncelleAsync(string catName, int catID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Category_kategoriBilgileriniGetir", ReplyAction="http://tempuri.org/IService1/Category_kategoriBilgileriniGetirResponse")]
        System.Data.DataTable Category_kategoriBilgileriniGetir(int catID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Category_kategoriBilgileriniGetir", ReplyAction="http://tempuri.org/IService1/Category_kategoriBilgileriniGetirResponse")]
        System.Threading.Tasks.Task<System.Data.DataTable> Category_kategoriBilgileriniGetirAsync(int catID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Category_kategorileriGetir", ReplyAction="http://tempuri.org/IService1/Category_kategorileriGetirResponse")]
        System.Data.DataTable Category_kategorileriGetir();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Category_kategorileriGetir", ReplyAction="http://tempuri.org/IService1/Category_kategorileriGetirResponse")]
        System.Threading.Tasks.Task<System.Data.DataTable> Category_kategorileriGetirAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Category_kategorileriSiraliGetir", ReplyAction="http://tempuri.org/IService1/Category_kategorileriSiraliGetirResponse")]
        System.Data.DataTable Category_kategorileriSiraliGetir();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Category_kategorileriSiraliGetir", ReplyAction="http://tempuri.org/IService1/Category_kategorileriSiraliGetirResponse")]
        System.Threading.Tasks.Task<System.Data.DataTable> Category_kategorileriSiraliGetirAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : ClientAnaSayfa.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<ClientAnaSayfa.ServiceReference1.IService1>, ClientAnaSayfa.ServiceReference1.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool Test() {
            return base.Channel.Test();
        }
        
        public System.Threading.Tasks.Task<bool> TestAsync() {
            return base.Channel.TestAsync();
        }
        
        public System.Data.DataTable TestDataTable() {
            return base.Channel.TestDataTable();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> TestDataTableAsync() {
            return base.Channel.TestDataTableAsync();
        }
        
        public string getDBVersion() {
            return base.Channel.getDBVersion();
        }
        
        public System.Threading.Tasks.Task<string> getDBVersionAsync() {
            return base.Channel.getDBVersionAsync();
        }
        
        public string Users_kullaniciEkle(string firstName, string lastName, string tcNo, string password, int role, string mail, string phoneNo, string address, int gender) {
            return base.Channel.Users_kullaniciEkle(firstName, lastName, tcNo, password, role, mail, phoneNo, address, gender);
        }
        
        public System.Threading.Tasks.Task<string> Users_kullaniciEkleAsync(string firstName, string lastName, string tcNo, string password, int role, string mail, string phoneNo, string address, int gender) {
            return base.Channel.Users_kullaniciEkleAsync(firstName, lastName, tcNo, password, role, mail, phoneNo, address, gender);
        }
        
        public bool Users_kullaniciSil(int userID) {
            return base.Channel.Users_kullaniciSil(userID);
        }
        
        public System.Threading.Tasks.Task<bool> Users_kullaniciSilAsync(int userID) {
            return base.Channel.Users_kullaniciSilAsync(userID);
        }
        
        public string Users_kullaniciGuncelle(string firstName, string lastName, string tcNo, string password, int role, string mail, string phoneNo, string address, int gender, int userID) {
            return base.Channel.Users_kullaniciGuncelle(firstName, lastName, tcNo, password, role, mail, phoneNo, address, gender, userID);
        }
        
        public System.Threading.Tasks.Task<string> Users_kullaniciGuncelleAsync(string firstName, string lastName, string tcNo, string password, int role, string mail, string phoneNo, string address, int gender, int userID) {
            return base.Channel.Users_kullaniciGuncelleAsync(firstName, lastName, tcNo, password, role, mail, phoneNo, address, gender, userID);
        }
        
        public System.Data.DataTable Users_kullanicilariGetir() {
            return base.Channel.Users_kullanicilariGetir();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> Users_kullanicilariGetirAsync() {
            return base.Channel.Users_kullanicilariGetirAsync();
        }
        
        public System.Data.DataTable Users_garsonlariGetir() {
            return base.Channel.Users_garsonlariGetir();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> Users_garsonlariGetirAsync() {
            return base.Channel.Users_garsonlariGetirAsync();
        }
        
        public System.Data.DataTable Users_yoneticileriGetir() {
            return base.Channel.Users_yoneticileriGetir();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> Users_yoneticileriGetirAsync() {
            return base.Channel.Users_yoneticileriGetirAsync();
        }
        
        public bool Users_kullaniciGiris(int userID, string password) {
            return base.Channel.Users_kullaniciGiris(userID, password);
        }
        
        public System.Threading.Tasks.Task<bool> Users_kullaniciGirisAsync(int userID, string password) {
            return base.Channel.Users_kullaniciGirisAsync(userID, password);
        }
        
        public bool Users_kullaniciVarmi(int userID) {
            return base.Channel.Users_kullaniciVarmi(userID);
        }
        
        public System.Threading.Tasks.Task<bool> Users_kullaniciVarmiAsync(int userID) {
            return base.Channel.Users_kullaniciVarmiAsync(userID);
        }
        
        public System.Data.DataTable Users_kullaniciBilgileriniGetir(int userID) {
            return base.Channel.Users_kullaniciBilgileriniGetir(userID);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> Users_kullaniciBilgileriniGetirAsync(int userID) {
            return base.Channel.Users_kullaniciBilgileriniGetirAsync(userID);
        }
        
        public string Users_kullaniciAdSoyadGetir(int userID) {
            return base.Channel.Users_kullaniciAdSoyadGetir(userID);
        }
        
        public System.Threading.Tasks.Task<string> Users_kullaniciAdSoyadGetirAsync(int userID) {
            return base.Channel.Users_kullaniciAdSoyadGetirAsync(userID);
        }
        
        public System.Data.DataTable Users_tumGarsonlarinAdSoyadlari() {
            return base.Channel.Users_tumGarsonlarinAdSoyadlari();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> Users_tumGarsonlarinAdSoyadlariAsync() {
            return base.Channel.Users_tumGarsonlarinAdSoyadlariAsync();
        }
        
        public string Tables_masaEkle(string tableNo, int capacity) {
            return base.Channel.Tables_masaEkle(tableNo, capacity);
        }
        
        public System.Threading.Tasks.Task<string> Tables_masaEkleAsync(string tableNo, int capacity) {
            return base.Channel.Tables_masaEkleAsync(tableNo, capacity);
        }
        
        public bool Tables_masaSil(int tableID) {
            return base.Channel.Tables_masaSil(tableID);
        }
        
        public System.Threading.Tasks.Task<bool> Tables_masaSilAsync(int tableID) {
            return base.Channel.Tables_masaSilAsync(tableID);
        }
        
        public string Tables_masaGuncelle(string tableNo, int capacity, int tableID) {
            return base.Channel.Tables_masaGuncelle(tableNo, capacity, tableID);
        }
        
        public System.Threading.Tasks.Task<string> Tables_masaGuncelleAsync(string tableNo, int capacity, int tableID) {
            return base.Channel.Tables_masaGuncelleAsync(tableNo, capacity, tableID);
        }
        
        public System.Data.DataTable Tables_masalariGetir() {
            return base.Channel.Tables_masalariGetir();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> Tables_masalariGetirAsync() {
            return base.Channel.Tables_masalariGetirAsync();
        }
        
        public System.Data.DataTable Tables_acikMasalariGetir() {
            return base.Channel.Tables_acikMasalariGetir();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> Tables_acikMasalariGetirAsync() {
            return base.Channel.Tables_acikMasalariGetirAsync();
        }
        
        public System.Data.DataTable Tables_bosMasalariGetir() {
            return base.Channel.Tables_bosMasalariGetir();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> Tables_bosMasalariGetirAsync() {
            return base.Channel.Tables_bosMasalariGetirAsync();
        }
        
        public System.Data.DataTable Tables_masaBilgileriniGetir(int tableID) {
            return base.Channel.Tables_masaBilgileriniGetir(tableID);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> Tables_masaBilgileriniGetirAsync(int tableID) {
            return base.Channel.Tables_masaBilgileriniGetirAsync(tableID);
        }
        
        public bool Tables_masaAc(int userID, int tableID) {
            return base.Channel.Tables_masaAc(userID, tableID);
        }
        
        public System.Threading.Tasks.Task<bool> Tables_masaAcAsync(int userID, int tableID) {
            return base.Channel.Tables_masaAcAsync(userID, tableID);
        }
        
        public string Tables_masaHesapGetir(int tableID) {
            return base.Channel.Tables_masaHesapGetir(tableID);
        }
        
        public System.Threading.Tasks.Task<string> Tables_masaHesapGetirAsync(int tableID) {
            return base.Channel.Tables_masaHesapGetirAsync(tableID);
        }
        
        public bool Tables_masaDurumGetir(int tableID) {
            return base.Channel.Tables_masaDurumGetir(tableID);
        }
        
        public System.Threading.Tasks.Task<bool> Tables_masaDurumGetirAsync(int tableID) {
            return base.Channel.Tables_masaDurumGetirAsync(tableID);
        }
        
        public bool Tables_masaKapat(int tableID) {
            return base.Channel.Tables_masaKapat(tableID);
        }
        
        public System.Threading.Tasks.Task<bool> Tables_masaKapatAsync(int tableID) {
            return base.Channel.Tables_masaKapatAsync(tableID);
        }
        
        public string Product_urunEkle(int catID, string productName, string price, string description) {
            return base.Channel.Product_urunEkle(catID, productName, price, description);
        }
        
        public System.Threading.Tasks.Task<string> Product_urunEkleAsync(int catID, string productName, string price, string description) {
            return base.Channel.Product_urunEkleAsync(catID, productName, price, description);
        }
        
        public string Product_urunSil(int productID) {
            return base.Channel.Product_urunSil(productID);
        }
        
        public System.Threading.Tasks.Task<string> Product_urunSilAsync(int productID) {
            return base.Channel.Product_urunSilAsync(productID);
        }
        
        public bool Product_urunSiparisleriyleSil(int product) {
            return base.Channel.Product_urunSiparisleriyleSil(product);
        }
        
        public System.Threading.Tasks.Task<bool> Product_urunSiparisleriyleSilAsync(int product) {
            return base.Channel.Product_urunSiparisleriyleSilAsync(product);
        }
        
        public bool Product_kategoridekiUrunleriSil(int catID) {
            return base.Channel.Product_kategoridekiUrunleriSil(catID);
        }
        
        public System.Threading.Tasks.Task<bool> Product_kategoridekiUrunleriSilAsync(int catID) {
            return base.Channel.Product_kategoridekiUrunleriSilAsync(catID);
        }
        
        public string Product_urunGuncelle(string productName, string price, int status, string description, int catID, int productID) {
            return base.Channel.Product_urunGuncelle(productName, price, status, description, catID, productID);
        }
        
        public System.Threading.Tasks.Task<string> Product_urunGuncelleAsync(string productName, string price, int status, string description, int catID, int productID) {
            return base.Channel.Product_urunGuncelleAsync(productName, price, status, description, catID, productID);
        }
        
        public System.Data.DataTable Product_urunleriGetir() {
            return base.Channel.Product_urunleriGetir();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> Product_urunleriGetirAsync() {
            return base.Channel.Product_urunleriGetirAsync();
        }
        
        public System.Data.DataTable Product_akfitUrunleriGetir() {
            return base.Channel.Product_akfitUrunleriGetir();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> Product_akfitUrunleriGetirAsync() {
            return base.Channel.Product_akfitUrunleriGetirAsync();
        }
        
        public System.Data.DataTable Product_kategoriyeGoreUrunleriGetir(int catID) {
            return base.Channel.Product_kategoriyeGoreUrunleriGetir(catID);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> Product_kategoriyeGoreUrunleriGetirAsync(int catID) {
            return base.Channel.Product_kategoriyeGoreUrunleriGetirAsync(catID);
        }
        
        public System.Data.DataTable Product_urunleriSiraliGetir() {
            return base.Channel.Product_urunleriSiraliGetir();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> Product_urunleriSiraliGetirAsync() {
            return base.Channel.Product_urunleriSiraliGetirAsync();
        }
        
        public System.Data.DataTable Product_kategoriyeGoreUrunleriSiraliGetir(int catID) {
            return base.Channel.Product_kategoriyeGoreUrunleriSiraliGetir(catID);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> Product_kategoriyeGoreUrunleriSiraliGetirAsync(int catID) {
            return base.Channel.Product_kategoriyeGoreUrunleriSiraliGetirAsync(catID);
        }
        
        public System.Data.DataTable Product_urunBilgileriniGetir(int productID) {
            return base.Channel.Product_urunBilgileriniGetir(productID);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> Product_urunBilgileriniGetirAsync(int productID) {
            return base.Channel.Product_urunBilgileriniGetirAsync(productID);
        }
        
        public string Product_urunFiyatGetir(int productID) {
            return base.Channel.Product_urunFiyatGetir(productID);
        }
        
        public System.Threading.Tasks.Task<string> Product_urunFiyatGetirAsync(int productID) {
            return base.Channel.Product_urunFiyatGetirAsync(productID);
        }
        
        public bool Product_urunDurumGuncelle(int status, int productID) {
            return base.Channel.Product_urunDurumGuncelle(status, productID);
        }
        
        public System.Threading.Tasks.Task<bool> Product_urunDurumGuncelleAsync(int status, int productID) {
            return base.Channel.Product_urunDurumGuncelleAsync(status, productID);
        }
        
        public bool Product_kategoriyeAitUrunKontrol(int catID) {
            return base.Channel.Product_kategoriyeAitUrunKontrol(catID);
        }
        
        public System.Threading.Tasks.Task<bool> Product_kategoriyeAitUrunKontrolAsync(int catID) {
            return base.Channel.Product_kategoriyeAitUrunKontrolAsync(catID);
        }
        
        public bool Orders_siparisEkle(int tableID, int productID, int catID, int total) {
            return base.Channel.Orders_siparisEkle(tableID, productID, catID, total);
        }
        
        public System.Threading.Tasks.Task<bool> Orders_siparisEkleAsync(int tableID, int productID, int catID, int total) {
            return base.Channel.Orders_siparisEkleAsync(tableID, productID, catID, total);
        }
        
        public string Orders_siparisSil(int tableID, int productID, int total) {
            return base.Channel.Orders_siparisSil(tableID, productID, total);
        }
        
        public System.Threading.Tasks.Task<string> Orders_siparisSilAsync(int tableID, int productID, int total) {
            return base.Channel.Orders_siparisSilAsync(tableID, productID, total);
        }
        
        public bool Orders_siparisUrunIDileSil(int productID) {
            return base.Channel.Orders_siparisUrunIDileSil(productID);
        }
        
        public System.Threading.Tasks.Task<bool> Orders_siparisUrunIDileSilAsync(int productID) {
            return base.Channel.Orders_siparisUrunIDileSilAsync(productID);
        }
        
        public string Orders_siparisIDileSil(int orderID) {
            return base.Channel.Orders_siparisIDileSil(orderID);
        }
        
        public System.Threading.Tasks.Task<string> Orders_siparisIDileSilAsync(int orderID) {
            return base.Channel.Orders_siparisIDileSilAsync(orderID);
        }
        
        public int Orders_siparisCATIDileSil(int catID) {
            return base.Channel.Orders_siparisCATIDileSil(catID);
        }
        
        public System.Threading.Tasks.Task<int> Orders_siparisCATIDileSilAsync(int catID) {
            return base.Channel.Orders_siparisCATIDileSilAsync(catID);
        }
        
        public string Orders_masaninTümSiparisleriniSil(int tableID) {
            return base.Channel.Orders_masaninTümSiparisleriniSil(tableID);
        }
        
        public System.Threading.Tasks.Task<string> Orders_masaninTümSiparisleriniSilAsync(int tableID) {
            return base.Channel.Orders_masaninTümSiparisleriniSilAsync(tableID);
        }
        
        public System.Data.DataTable Orders_siparisleriGetir() {
            return base.Channel.Orders_siparisleriGetir();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> Orders_siparisleriGetirAsync() {
            return base.Channel.Orders_siparisleriGetirAsync();
        }
        
        public System.Data.DataTable Orders_masayaAitSiparisleriGetir(int tableID) {
            return base.Channel.Orders_masayaAitSiparisleriGetir(tableID);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> Orders_masayaAitSiparisleriGetirAsync(int tableID) {
            return base.Channel.Orders_masayaAitSiparisleriGetirAsync(tableID);
        }
        
        public bool Orders_urunKontrol(int productID) {
            return base.Channel.Orders_urunKontrol(productID);
        }
        
        public System.Threading.Tasks.Task<bool> Orders_urunKontrolAsync(int productID) {
            return base.Channel.Orders_urunKontrolAsync(productID);
        }
        
        public bool Orders_masaUrunKontrol(int productID, int tableID) {
            return base.Channel.Orders_masaUrunKontrol(productID, tableID);
        }
        
        public System.Threading.Tasks.Task<bool> Orders_masaUrunKontrolAsync(int productID, int tableID) {
            return base.Channel.Orders_masaUrunKontrolAsync(productID, tableID);
        }
        
        public System.Data.DataTable DayReport_guneAitRaporGetir(string date) {
            return base.Channel.DayReport_guneAitRaporGetir(date);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> DayReport_guneAitRaporGetirAsync(string date) {
            return base.Channel.DayReport_guneAitRaporGetirAsync(date);
        }
        
        public System.Data.DataTable DayReport_raporlariGetir() {
            return base.Channel.DayReport_raporlariGetir();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> DayReport_raporlariGetirAsync() {
            return base.Channel.DayReport_raporlariGetirAsync();
        }
        
        public string[] DayReport_guneAitCalisanIsimleri(string date) {
            return base.Channel.DayReport_guneAitCalisanIsimleri(date);
        }
        
        public System.Threading.Tasks.Task<string[]> DayReport_guneAitCalisanIsimleriAsync(string date) {
            return base.Channel.DayReport_guneAitCalisanIsimleriAsync(date);
        }
        
        public string Category_kategoriEkle(string catName) {
            return base.Channel.Category_kategoriEkle(catName);
        }
        
        public System.Threading.Tasks.Task<string> Category_kategoriEkleAsync(string catName) {
            return base.Channel.Category_kategoriEkleAsync(catName);
        }
        
        public string Category_kategoriSil(int catID) {
            return base.Channel.Category_kategoriSil(catID);
        }
        
        public System.Threading.Tasks.Task<string> Category_kategoriSilAsync(int catID) {
            return base.Channel.Category_kategoriSilAsync(catID);
        }
        
        public string Category_kategoriUrunleriyleSil(int catID) {
            return base.Channel.Category_kategoriUrunleriyleSil(catID);
        }
        
        public System.Threading.Tasks.Task<string> Category_kategoriUrunleriyleSilAsync(int catID) {
            return base.Channel.Category_kategoriUrunleriyleSilAsync(catID);
        }
        
        public string Category_kategoriGuncelle(string catName, int catID) {
            return base.Channel.Category_kategoriGuncelle(catName, catID);
        }
        
        public System.Threading.Tasks.Task<string> Category_kategoriGuncelleAsync(string catName, int catID) {
            return base.Channel.Category_kategoriGuncelleAsync(catName, catID);
        }
        
        public System.Data.DataTable Category_kategoriBilgileriniGetir(int catID) {
            return base.Channel.Category_kategoriBilgileriniGetir(catID);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> Category_kategoriBilgileriniGetirAsync(int catID) {
            return base.Channel.Category_kategoriBilgileriniGetirAsync(catID);
        }
        
        public System.Data.DataTable Category_kategorileriGetir() {
            return base.Channel.Category_kategorileriGetir();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> Category_kategorileriGetirAsync() {
            return base.Channel.Category_kategorileriGetirAsync();
        }
        
        public System.Data.DataTable Category_kategorileriSiraliGetir() {
            return base.Channel.Category_kategorileriSiraliGetir();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> Category_kategorileriSiraliGetirAsync() {
            return base.Channel.Category_kategorileriSiraliGetirAsync();
        }
    }
}
